### ISSUE TITLE
Input and output files

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/chem-sampler#11]
We need to have an easy way of inputing smiles and getting the output. 
The current dummy.py just prints the output in the screen, we should have a src/sampler.py file which accepts as argvs

- Input file: csv file with list of smiles
- Output file: csv file with the input smiles as the first column and the sampled smiles in columns

**Comment by anamika-yadav99** [comment]
Hi @GemmaTuron I have added a script sampler,py in src which you can run to pass in input and output file. I did not make any changes to the chem sampler module for now because it would require a lot to be changed. API function would be more versatile to have. However if you prefer the other way, I can make the changes. 
You can run ` python sampler.py './in.csv' './out.csv' --SAMPLER ChemblSampler --NUM_SAMPLES 100 ` in src directory

**Comment by GemmaTuron** [comment]
Hi @anamika-yadav99 

When I try to clone the repo the sampler.py file is not cloned. I've tried several times so I am not sure what is going on but it seems the file is not git tracked

**Comment by GemmaTuron** [comment]
That works perfectly thanks @anamika-yadav99
